schema = 1

[dependencies]
"akira-tl/matt-skills/code-review" = "*"
"akira-tl/matt-skills/codebase-design" = "*"
"akira-tl/matt-skills/diagnosing-bugs" = "*"
"akira-tl/matt-skills/domain-modeling" = "*"
"akira-tl/matt-skills/grill-me" = "*"
"akira-tl/matt-skills/grill-with-docs" = "*"
"akira-tl/matt-skills/grilling" = "*"
"akira-tl/matt-skills/handoff" = "*"
"akira-tl/matt-skills/implement" = "*"
"akira-tl/matt-skills/improve-codebase-architecture" = "*"
"akira-tl/matt-skills/prototype" = "*"
"akira-tl/matt-skills/research" = "*"
"akira-tl/matt-skills/resolving-merge-conflicts" = "*"
"akira-tl/matt-skills/setup-matt-pocock-skills" = "*"
"akira-tl/matt-skills/tdd" = "*"
"akira-tl/matt-skills/teach" = "*"
"akira-tl/matt-skills/to-questionnaire" = "*"
"akira-tl/matt-skills/to-spec" = "*"
"akira-tl/matt-skills/to-tickets" = "*"
"akira-tl/matt-skills/triage" = "*"
"akira-tl/matt-skills/wait-what" = "*"
"akira-tl/matt-skills/wayfinder" = "*"
"akira-tl/matt-skills/wizard" = "*"
"akira-tl/matt-skills/writing-for-agents" = "*"
